const METALS = {
  XAU: {
    symbol: 'XAU',
    name: 'Gold',
    unit: 'oz',
    fmpSymbol: 'GCUSD',
    yahooSymbol: 'GC=F',
    order: 1,
    isMetal: true,
  },
  XAG: {
    symbol: 'XAG',
    name: 'Silver',
    unit: 'oz',
    fmpSymbol: 'SIUSD',
    yahooSymbol: 'SI=F',
    order: 2,
    isMetal: true,
  },
  XPT: {
    symbol: 'XPT',
    name: 'Platinum',
    unit: 'oz',
    fmpSymbol: 'PLUSD',
    yahooSymbol: 'PL=F',
    order: 3,
    isMetal: true,
  },
  XPD: {
    symbol: 'XPD',
    name: 'Palladium',
    unit: 'oz',
    fmpSymbol: 'PAUSD',
    yahooSymbol: 'PA=F',
    order: 4,
    isMetal: true,
  },
  BTC: {
    symbol: 'BTC',
    name: 'Bitcoin',
    unit: 'coin',
    fmpSymbol: 'BTCUSD',
    yahooSymbol: 'BTC-USD',
    order: 5,
    isMetal: false,
    isCrypto: true,
  },
  OIL: {
    symbol: 'OIL',
    name: 'Crude Oil',
    unit: 'barrel',
    fmpSymbol: 'CLUSD',
    yahooSymbol: 'CL=F',
    order: 6,
    isMetal: false,
    isCommodity: true,
  },
  USD: {
    symbol: 'USD',
    name: 'US Dollar Index',
    unit: 'index',
    fmpSymbol: 'DX',
    yahooSymbol: 'DX-Y.NYB',
    order: 7,
    isMetal: false,
    isCurrency: true,
  },
  HG: {
    symbol: 'HG',
    name: 'Copper',
    unit: 'lb',
    fmpSymbol: 'HGUSD',
    yahooSymbol: 'HG=F',
    order: 8,
    isMetal: true,
  },
  SPX: {
    symbol: 'SPX',
    name: 'S&P 500',
    unit: 'index',
    fmpSymbol: 'SPY',
    yahooSymbol: '^GSPC',
    order: 9,
    isMetal: false,
    isIndex: true,
  },
};

const METAL_SYMBOLS = Object.keys(METALS);

module.exports = { METALS, METAL_SYMBOLS };
